name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Environment Variable
      run: echo "DJANGO_SUPERUSER_PASSWORD=yes" >> $GITHUB_ENV
    - name: Install Dependencies
      run: |
        pip install django
        pip install selenium
    - name: Install ChromeDriver
      run: |
        CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        curl -sS -o chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver.zip -d $HOME
        echo "export PATH=$HOME:$PATH" >> $GITHUB_ENV
      shell: bash
    - name: Run Tests
      run: |
        python3 manage.py collectstatic --noinput
        python3 manage.py test
