name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run network application tests
      run: |
        pip install django
        pip install selenium
        python3 manage.py collectstatic
        python3 manage.py test